apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-configmap
data:
  init.sql: |
{{ .Files.Get "files/init.sql" | indent 4 }}
  database_host: {{ .Release.Name }}-db-service
  database_port: "{{ .Values.service.port }}"
  database_name: {{ .Values.database.name }}