apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.backend.name }}-service
spec:
  selector:
    app: {{ .Values.global.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.global.backend.port }}
      targetPort: {{ .Values.global.backend.port }}